rm checksums before copying it

diff --git a/.github/workflows/integration.yaml b/.github/workflows/integration.yaml
--- a/.github/workflows/integration.yaml
+++ b/.github/workflows/integration.yaml
@@ -453,9 +453,12 @@ jobs:
           ls -lh /nix/store/m8j5gz5l1d5yjf6ii3yk204hsgdw6fmv-source/wasm/
           echo "cat checksums.json"
           cat /nix/store/m8j5gz5l1d5yjf6ii3yk204hsgdw6fmv-source/wasm/checksums.json
+          echo "will ls"
           ls -lh /tmp/namada-repo/wasm/
+          echo "will chmod to rm"
+          chmod u+w /tmp/namada-repo/wasm/checksums.json
           echo "rm checksums.json"
-          rm /tmp/namada-repo/wasm/checksums.json
+          rm /tmp/namada-repo/wasm/checksums.json || echo "failed to rm: $?"
           echo "copy with cat checksums.json"
           cat /nix/store/m8j5gz5l1d5yjf6ii3yk204hsgdw6fmv-source/wasm/checksums.json > /tmp/namada-repo/wasm/checksums.json
           echo "rsync checksums.json done"
