Debug

diff --git a/.github/workflows/integration.yaml b/.github/workflows/integration.yaml
--- a/.github/workflows/integration.yaml
+++ b/.github/workflows/integration.yaml
@@ -443,13 +443,13 @@ jobs:
       - name: Fix permissions for Namada repository
         id: namada-permissions
         run: |
-          set -x
+          set -euxo pipefail
           ls -lh ${{ steps.namada-repo-path.outputs.NAMADA_REPO_PATH }}/wasm
           echo "rsync"
           rsync -av --exclude='proto' ${{ steps.namada-repo-path.outputs.NAMADA_REPO_PATH }} /tmp/namada-repo || echo "rsync encountered an error"
           echo "done"
-          ls -lh /tmp/namada-repo
-          chmod -R 777 /tmp/namada-repo
+          ls -lh /tmp/namada-repo || (echo "ls failed"; exit 1)
+          chmod -R 777 /tmp/namada-repo || (echo "chmod failed"; exit 1)
           echo "NAMADA_REPO_PATH=/tmp/namada-repo" >> "$GITHUB_OUTPUT"
       - name: Download CometBFT
         run: |
