Add trailing slash to rsync content

diff --git a/.github/workflows/integration.yaml b/.github/workflows/integration.yaml
--- a/.github/workflows/integration.yaml
+++ b/.github/workflows/integration.yaml
@@ -446,7 +446,7 @@ jobs:
           set -euxo pipefail
           ls -lh ${{ steps.namada-repo-path.outputs.NAMADA_REPO_PATH }}/wasm
           echo "rsync"
-          rsync -av --exclude='proto' ${{ steps.namada-repo-path.outputs.NAMADA_REPO_PATH }} /tmp/namada-repo || echo "rsync encountered an error"
+          rsync -av --exclude='proto' ${{ steps.namada-repo-path.outputs.NAMADA_REPO_PATH }}/ /tmp/namada-repo || echo "rsync encountered an error"
           echo "done"
           ls -lh /tmp/namada-repo || (echo "ls failed"; exit 1)
           chmod -R 777 /tmp/namada-repo || (echo "chmod failed"; exit 1)
