DEbug

diff --git a/.github/workflows/integration.yaml b/.github/workflows/integration.yaml
--- a/.github/workflows/integration.yaml
+++ b/.github/workflows/integration.yaml
@@ -445,7 +445,7 @@ jobs:
         run: |
           set -euxo pipefail
           ls -lh ${{ steps.namada-repo-path.outputs.NAMADA_REPO_PATH }}/wasm
-          rsync -av --exclude='proto' ${{ steps.namada-repo-path.outputs.NAMADA_REPO_PATH }}/ /tmp/namada-repo || echo "rsync encountered an error"
+          rsync -av ${{ steps.namada-repo-path.outputs.NAMADA_REPO_PATH }}/ /tmp/namada-repo || echo "rsync encountered an error"
           ls -lh /tmp/namada-repo || (echo "ls failed"; exit 1)
           chmod -R 777 /tmp/namada-repo || (echo "chmod failed"; exit 1)
           echo "NAMADA_REPO_PATH=/tmp/namada-repo" >> "$GITHUB_OUTPUT"
